const STORAGE_KEYS = {
  ROUTES: 'ROUTE_LAB_ROUTES',
  RECENT_SETTINGS: 'ROUTE_LAB_RECENT_SETTINGS',
  OFFLINE_QUEUE: 'ROUTE_LAB_OFFLINE_QUEUE',
  AUTH_TOKEN: 'ROUTE_LAB_AUTH_TOKEN',
  LAST_SYNC_AT: 'ROUTE_LAB_LAST_SYNC_AT',
  USER_PROFILE: 'ROUTE_LAB_USER_PROFILE',
  WEATHER_SNAPSHOT: 'ROUTE_LAB_WEATHER_SNAPSHOT',
  GEOCODE_CACHE: 'ROUTE_LAB_GEOCODE_CACHE',
  LAST_KNOWN_CITY: 'ROUTE_LAB_LAST_KNOWN_CITY',
  USER_PROFILE_SYNC: 'ROUTE_LAB_USER_PROFILE_SYNC',
  USER_ACCOUNT: 'ROUTE_LAB_USER_ACCOUNT',
  KEEP_SCREEN_ON: 'ROUTE_LAB_KEEP_SCREEN_ON',
  USER_ACHIEVEMENTS: 'ROUTE_LAB_USER_ACHIEVEMENTS',
  LATEST_ANNOUNCEMENT: 'ROUTE_LAB_LATEST_ANNOUNCEMENT',
  THEME_PREFERENCE: 'ROUTE_LAB_THEME_PREFERENCE',
  ROUTE_FEEDBACK_DRAFTS: 'ROUTE_LAB_ROUTE_FEEDBACK_DRAFTS',
};

module.exports = {
  STORAGE_KEYS,
};
